version: '3'

services:
  api:
    container_name: api
    image: node:18-alpine
    working_dir: /usr/src/api
    command: sh -c "yarn install && yarn dev"
    ports:
      - "3001:3001"
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules

  app:
    container_name: app
    image: node:18-alpine
    working_dir: /usr/src/app
    command: sh -c "yarn install && yarn dev"
    ports:
      - "5173:5173"
    volumes:
      - ./app:/usr/src/app
      - node_modules_app:/usr/src/app/node_modules
    depends_on:
      - api

volumes:
  node_modules_app: